version: "3"


services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - ${APP_EXTERNAL_PORT}:80
    volumes: 
        - "${APP_SRC_FOLDER}:/app"
    env_file: ".env"
    
